# Generated by Django 5.1.3 on 2024-12-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
